### ISSUE TITLE
Friend list parsing

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/RatTracker#23]
Friends list parsing is what enables us to detect FR requests from our clients.
When a FR is sent, it shows up in state "pending" in the FriendRequest XML in Netlog. Commander names are encoded as UTF8 hex in the <name> tag. We match this to our client's name.

Accepting the friend request produces a new friendrequest update with a status code that we can detect and then trigger a FR+ notification.

Current status is mostly implemented; needs additional sanity checks and ensuring that it matches to the active client.

**Comment by andybish** [comment]
testing webhook (derp, dropped an s), but also friend events are in the journals now, including incoming friend requests and accepts

**Comment by Adanaran** [comment]
This has been resolved in the rewrite by using the new journal events.
