### ISSUE TITLE
Overlay does not obey ED monitor preference.

### ISSUE THREAD

**Issue by SuperManifolds** [FuelRats/RatTracker#42]
RatTracker will always use the primary monitor of the computer even when ED is set to use another monitor.

![Example](https://sorlie.co.uk/d/Capture.JPG)

**Comment by kenneaal** [comment]
Unable to directly associate E:D display enumeration with the way we name monitors. Setting added for changing which display the overlay appears on.

[--- Commented from Asana.com
#commenter Kenneth Aalberg
---[aa]
