### ISSUE TITLE
Refactor case tracking

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/RatTracker#8]
Currently, the case you are on is tracked rather haphardlessly through an instance of ClientInfo, myClient. This could use considerable cleanup.
- Redesign ClientInfo class to include a link to the Rescue - probably by referencing the rescue ID. 
- Add flags for FR received/accepted, WR received/acccepted, Beacon, Sys and Instance+ to the ClientInfo class. 
- Link FR, WR, BC, SYS and INST buttons on the UI to data in myClient. NOTE THAT SOME OF THESE CAN'T BE BOOLS. FR can be in state "not received", "received", and "accepted". It should also have the current ability of clicking the FR/WR/BC/SYS/INST buttons to override the reported state (Back to not recieved, or to accepted).
- Prepare event handler for those properties changing to push the updates back to the API.

**Comment by Adanaran** [comment]
Addition: And has to be able to gracefully handle the rescue going into status CLOSED, in which case it should clear the active case.

**Comment by kenneaal** [comment]
Refactored to bindings. Reports progress to API with 3PM. Could use a "paperwork" button, but this is for 1.5 or later.
